#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.


# Make some directories
mkdir -p ${OPENSHIFT_DATA_DIR}/post
mkdir -p ${OPENSHIFT_DATA_DIR}/logs

for i in static/img static/lang static/ww; do
    # Ensure the directories exist
    mkdir -p ${OPENSHIFT_DATA_DIR}/${i}
    # Before linking them
    ln -sfT ${OPENSHIFT_DATA_DIR}/${i} ${OPENSHIFT_REPO_DIR}/${i}
done

mkdir -p ${OPENSHIFT_REPO_DIR}/wsgi
ln -sft ${OPENSHIFT_REPO_DIR}/wsgi ${OPENSHIFT_REPO_DIR}/static

#ln -sf ${OPENSHIFT_DATA_DIR}/static/favicon.ico ${OPENSHIFT_REPO_DIR}/static/favicon.ico


# Minify some js/css
if [ -x ${OPENSHIFT_DATA_DIR}/bin/yuicompressor-2.4.8.jar ] && which java 2>&1 > /dev/null; then
    for INFILE in $(find "${OPENSHIFT_REPO_DIR}/static" -type l -iname "*.min.*"); do
        REALFILE=$(readlink -f ${INFILE})
        OUTFILE=${INFILE}.tmp
        if java -jar ${OPENSHIFT_DATA_DIR}/bin/yuicompressor-2.4.8.jar -o ${OUTFILE} ${INFILE}; then
            if [ $(stat -c%s ${OUTFILE}) -lt $(stat -c%s ${REALFILE}) ]; then
                mv ${OUTFILE} ${INFILE}
            fi
        else
            echo "Error occured while minifying ${INFILE}"
        fi
    done
else
    echo "Minifier not found"
fi


# Use repository htaccess if exists
if [ -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ]; then
  cp -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ${OPENSHIFT_REPO_DIR}/.htaccess
fi


set -e

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
    echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi


# Confirm database exists, if not create it
if ! mysql -u"${OPENSHIFT_MYSQL_DB_USERNAME}" -p"${OPENSHIFT_MYSQL_DB_PASSWORD}" -h"${OPENSHIFT_MYSQL_DB_HOST}" -P"${OPENSHIFT_MYSQL_DB_PORT}" -e "show tables;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo "Database schema not yet added." 1>&2
else
    echo "Database appears to be configured."
fi


### EOF ##
